export const GET_ALL_POSTS = 'GET_ALL_POSTS';
export const GET_POSTS = 'GET_POSTS';
export const POST_POST = 'POST_POST';
export const PUT_POST = 'EDIT_POST';
export const DELETE_POST = 'DELETE_POST';

export const POST_VOTE_POST = 'POST_VOTE_POST';
// export const POST_DOWNVOTE_POST = 'POST_DOWNVOTE_POST'

export const GET_COMMENT = 'GET_COMMENT';
export const POST_COMMENT = 'POST_COMMENT';
export const PUT_COMMENT = 'PUT_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';

export const POST_UPVOTE_COMMENT = 'POST_UPVOTE_COMMENT';
// export const POST_DOWNVOTE_COMMENT = 'POST_DOWNVOTE_COMMENT'
